run sample against LocalStack + add query-lambda function for testing
localstack/amazon-rds-init-cdk pull request #1
Opened 2023-05-16 16:27 UTC by steffyP

2023-05-22 16:00 UTC, HarshCasper requested changes

2023-05-22 16:12 UTC, steffyP commented on demos/rds-init-example.ts
> +      runtime: lambda.Runtime.NODEJS_16_X,
Initially I wanted to, but it doesn't seem to be an option? At least it's not defined as Runtime-static variable. Also checked the latest release (which is from today) 🤷‍♀️

2023-05-22 16:24 UTC, steffyP commented on README.md
> +
I actually moved it down intentionally, as it is important to start LocalStack with the API-key first :) 
I would rather leave it that way, so people do not get confused. WDYT?

2023-05-24 15:37 UTC, steffyP commented on README.md
> +The Amazon RDS initialization using CDK sample application demonstrates how LocalStack supports RDS instances initialization using CDK and CloudFormation Custom Resources. The sample application impl
```suggestion
The Amazon RDS initialization using CDK sample application demonstrates how LocalStack supports RDS instances initialization using CDK and CloudFormation Custom Resources. The sample application implements a Node.js Lambda function for compute layer, which is able to run custom SQL scripts. It also executes custom commands supported by the [Node.js client for MySQL2](https://www.npmjs.com/package/mysql2). To test this application sample, we will demonstrate how you use LocalStack to deploy the infrastructure on your developer machine and your CI environment and use a Lambda function to run queries against the RDS database after successful deployment.
```

2023-05-24 15:45 UTC, merged